version: "3.1"

services:
  pingfederate:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingdirectory:1389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=oauthplayground-ciba/pingfederate
      - SERVER_PROFILE_PARENT=BASELINE
      - SERVER_PROFILE_BASELINE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_BASELINE_PATH=baseline/pingfederate 
      - OOBAUTH_FROM_EMAIL_ADDRESS=slaxor@mail.ru
      - OOBAUTH_EMAIL_SMTP_HOST=smtp.mail.ru
      - OOBAUTH_EMAIL_SMTP_PORT=465
      - OOBAUTH_EMAIL_SMTP_USERNAME=slaxor@mail.ru
      - OOBAUTH_EMAIL_SMTP_PASSWORD=na6Su2XB7BRBn27Cebjd
      - PF_LOG_LEVEL=DEBUG
      - PING_DEBUG=true
    env_file:
      - ~/.pingidentity/devops         
   #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/volumes/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal

  pingdirectory:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=oauthplayground-ciba/pingdirectory
      - SERVER_PROFILE_PARENT=BASELINE
      - SERVER_PROFILE_BASELINE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_BASELINE_PATH=baseline/pingdirectory
    env_file:
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 1636:1636
      - 1443:1443
      - 1389:1389
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:${PING_IDENTITY_DEVOPS_TAG}
    ports:
      - 8443:8443
    networks: 
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz:
